name: TigerBeetle Server
description: Run a TigerBeetle server instance
author: GitHub Actions

# Define your inputs here.
inputs:
  cluster:
    description: The cluster ID for TigerBeetle
    required: false
    default: "0"
  replica:
    description: The replica ID for TigerBeetle
    required: false
    default: "0"
  replica-count:
    description: The number of replicas in the cluster
    required: false
    default: "1"
  port:
    description: The port to run TigerBeetle on
    required: false
    default: "3000"

# Define your outputs here.
outputs:
  status:
    description: The status of the TigerBeetle server
  port:
    description: The port the TigerBeetle server is running on

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_CLUSTER: ${{ inputs.cluster }}
    INPUT_REPLICA: ${{ inputs.replica }}
    INPUT_REPLICA_COUNT: ${{ inputs.replica-count }}
    INPUT_PORT: ${{ inputs.port }}
